<?php

namespace Database\Seeders;

use App\Models\MediaAsset;
use App\Models\Vocabulary;
use Illuminate\Database\Seeder;

class HskMediaAssetSeeder extends Seeder
{
    public function run(): void
    {
        $defaultAttribution = 'Designed with OpenMoji open-source assets and Learn Chinese pedagogic illustrations. Licensed under CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/).';

        $assets = [
            // ==================== ACTIONS ====================
            [
                'slug'        => 'actions-pao-bu',
                'name'        => 'Chạy bộ (Running)',
                'file_path'   => 'images/hsk/assets/actions/pao_bu.svg',
                'category'    => MediaAsset::CATEGORY_ACTIONS,
                'alt_text'    => 'Người đang chạy bộ thể dục',
                'keywords'    => ['chạy bộ', 'running', '跑步', 'pǎobù', '运动', '锻炼', '公园'],
                'vocabs'      => ['跑步', '跑', '运动'],
                'hsk_levels'  => [2, 3],
            ],
            [
                'slug'        => 'actions-youyong',
                'name'        => 'Bơi lội (Swimming)',
                'file_path'   => 'images/hsk/assets/actions/youyong.svg',
                'category'    => MediaAsset::CATEGORY_ACTIONS,
                'alt_text'    => 'Người đang bơi lội dưới nước',
                'keywords'    => ['bơi lội', 'swimming', '游泳', 'yóuyǒng', '水', '游泳馆'],
                'vocabs'      => ['游泳', '水'],
                'hsk_levels'  => [2, 3],
            ],
            [
                'slug'        => 'actions-ti-zuqiu',
                'name'        => 'Đá bóng (Playing Soccer)',
                'file_path'   => 'images/hsk/assets/actions/ti_zuqiu.svg',
                'category'    => MediaAsset::CATEGORY_ACTIONS,
                'alt_text'    => 'Quả bóng đá và cầu thủ đá bóng',
                'keywords'    => ['đá bóng', 'soccer', 'football', '踢足球', 'tī zúqiú', '足球', '运动'],
                'vocabs'      => ['踢足球', '足球'],
                'hsk_levels'  => [2, 3],
            ],
            [
                'slug'        => 'actions-chang-ge',
                'name'        => 'Ca hát (Singing)',
                'file_path'   => 'images/hsk/assets/actions/chang_ge.svg',
                'category'    => MediaAsset::CATEGORY_ACTIONS,
                'alt_text'    => 'Micro và nốt nhạc ca hát',
                'keywords'    => ['ca hát', 'singing', '唱歌', 'chàng gē', '音乐', '好听'],
                'vocabs'      => ['唱歌', '歌'],
                'hsk_levels'  => [2, 3],
            ],
            [
                'slug'        => 'actions-tiao-wu',
                'name'        => 'Khiêu vũ / Nhảy múa (Dancing)',
                'file_path'   => 'images/hsk/assets/actions/tiao_wu.svg',
                'category'    => MediaAsset::CATEGORY_ACTIONS,
                'alt_text'    => 'Vũ công đang khiêu vũ nhảy múa',
                'keywords'    => ['khiêu vũ', 'nhảy múa', 'dancing', '跳舞', 'tiàowǔ', '音乐'],
                'vocabs'      => ['跳舞'],
                'hsk_levels'  => [2, 3],
            ],
            [
                'slug'        => 'actions-jianshen',
                'name'        => 'Tập thể dục / Tập gym (Fitness)',
                'file_path'   => 'images/hsk/assets/actions/jianshen.svg',
                'category'    => MediaAsset::CATEGORY_ACTIONS,
                'alt_text'    => 'Tập tạ rèn luyện thể chất',
                'keywords'    => ['tập gym', 'fitness', 'workout', '健身', 'jiànshēn', '锻炼', '身体', '健康'],
                'vocabs'      => ['锻炼', '身体', '健康'],
                'hsk_levels'  => [2, 3],
            ],
            [
                'slug'        => 'actions-pashan',
                'name'        => 'Leo núi (Hiking / Mountain Climbing)',
                'file_path'   => 'images/hsk/assets/actions/pashan.svg',
                'category'    => MediaAsset::CATEGORY_ACTIONS,
                'alt_text'    => 'Người leo núi dã ngoại',
                'keywords'    => ['leo núi', 'hiking', 'climbing', '爬山', 'páshān', '山', '运动'],
                'vocabs'      => ['爬山', '山'],
                'hsk_levels'  => [3],
            ],
            [
                'slug'        => 'actions-chufang',
                'name'        => 'Nấu ăn trong bếp (Cooking)',
                'file_path'   => 'images/hsk/assets/actions/chufang.svg',
                'category'    => MediaAsset::CATEGORY_ACTIONS,
                'alt_text'    => 'Nấu nướng chảo thức ăn trong bếp',
                'keywords'    => ['nấu ăn', 'cooking', '做菜', 'zuò cài', '做饭', '厨房', '好吃'],
                'vocabs'      => ['厨房', '菜'],
                'hsk_levels'  => [3],
            ],
            [
                'slug'        => 'actions-dasaoba',
                'name'        => 'Quét dọn vệ sinh (Cleaning)',
                'file_path'   => 'images/hsk/assets/actions/dasaoba.svg',
                'category'    => MediaAsset::CATEGORY_ACTIONS,
                'alt_text'    => 'Chổi và dụng cụ quét dọn sạch sẽ',
                'keywords'    => ['quét dọn', 'dọn dẹp', 'cleaning', '打扫', 'dǎsǎo', '干净', '房间'],
                'vocabs'      => ['打扫', '干净'],
                'hsk_levels'  => [3],
            ],
            [
                'slug'        => 'actions-kan-shu',
                'name'        => 'Đọc sách (Reading Book)',
                'file_path'   => 'images/hsk/assets/actions/kan_shu.svg',
                'category'    => MediaAsset::CATEGORY_ACTIONS,
                'alt_text'    => 'Người ngồi đọc sách',
                'keywords'    => ['đọc sách', 'reading', '看书', 'kàn shū', '书', '学习'],
                'vocabs'      => ['看', '书'],
                'hsk_levels'  => [1, 2],
            ],
            [
                'slug'        => 'actions-chi-fan',
                'name'        => 'Ăn cơm (Eating Meal)',
                'file_path'   => 'images/hsk/assets/actions/chi_fan.svg',
                'category'    => MediaAsset::CATEGORY_ACTIONS,
                'alt_text'    => 'Bát cơm và đôi đũa',
                'keywords'    => ['ăn cơm', 'ăn uống', 'eating', '吃饭', 'chī fàn', '米饭', '菜'],
                'vocabs'      => ['吃', '米饭'],
                'hsk_levels'  => [1, 2],
            ],
            [
                'slug'        => 'actions-da-dianhua',
                'name'        => 'Gọi điện thoại (Making Phone Call)',
                'file_path'   => 'images/hsk/assets/actions/da_dianhua.svg',
                'category'    => MediaAsset::CATEGORY_ACTIONS,
                'alt_text'    => 'Người nghe gọi điện thoại',
                'keywords'    => ['gọi điện thoại', 'calling', '打电话', 'dǎ diànhuà', '电话', '手机'],
                'vocabs'      => ['打电话', '电话'],
                'hsk_levels'  => [1, 2],
            ],
            [
                'slug'        => 'actions-shuijiao',
                'name'        => 'Đi ngủ / Nghỉ ngơi (Sleeping)',
                'file_path'   => 'images/hsk/assets/actions/shuijiao.svg',
                'category'    => MediaAsset::CATEGORY_ACTIONS,
                'alt_text'    => 'Người nằm ngủ trên giường',
                'keywords'    => ['đi ngủ', 'ngủ', 'sleeping', '睡觉', 'shuìjiào', '床', '休息'],
                'vocabs'      => ['睡觉', '休息'],
                'hsk_levels'  => [1, 2],
            ],

            // ==================== ANIMALS ====================
            [
                'slug'        => 'animals-mao',
                'name'        => 'Con mèo (Cat)',
                'file_path'   => 'images/hsk/assets/animals/mao.svg',
                'category'    => MediaAsset::CATEGORY_ANIMALS,
                'alt_text'    => 'Chú mèo dễ thương',
                'keywords'    => ['con mèo', 'cat', '猫', 'māo', '小猫', '动物'],
                'vocabs'      => ['猫'],
                'hsk_levels'  => [1],
            ],
            [
                'slug'        => 'animals-gou',
                'name'        => 'Con chó (Dog)',
                'file_path'   => 'images/hsk/assets/animals/gou.svg',
                'category'    => MediaAsset::CATEGORY_ANIMALS,
                'alt_text'    => 'Chú chó nhỏ',
                'keywords'    => ['con chó', 'dog', '狗', 'gǒu', '小狗', '动物'],
                'vocabs'      => ['狗'],
                'hsk_levels'  => [1],
            ],

            // ==================== TRANSPORT ====================
            [
                'slug'        => 'transport-zixingche',
                'name'        => 'Xe đạp (Bicycle)',
                'file_path'   => 'images/hsk/assets/transport/zixingche.svg',
                'category'    => MediaAsset::CATEGORY_TRANSPORT,
                'alt_text'    => 'Chiếc xe đạp hai bánh',
                'keywords'    => ['xe đạp', 'bicycle', 'bike', '自行车', 'zìxíngchē', '骑车', '交通'],
                'vocabs'      => ['自行车', '骑'],
                'hsk_levels'  => [2, 3],
            ],
            [
                'slug'        => 'transport-qiche',
                'name'        => 'Ô tô (Car)',
                'file_path'   => 'images/hsk/assets/transport/qiche.svg',
                'category'    => MediaAsset::CATEGORY_TRANSPORT,
                'alt_text'    => 'Chiếc xe ô tô hơi',
                'keywords'    => ['ô tô', 'xe hơi', 'car', '汽车', 'qìchē', '开车', '车'],
                'vocabs'      => ['车'],
                'hsk_levels'  => [2, 3],
            ],
            [
                'slug'        => 'transport-chuzuche',
                'name'        => 'Xe taxi (Taxi)',
                'file_path'   => 'images/hsk/assets/transport/chuzuche.svg',
                'category'    => MediaAsset::CATEGORY_TRANSPORT,
                'alt_text'    => 'Chiếc xe taxi màu vàng',
                'keywords'    => ['taxi', 'xe taxi', 'cab', '出租车', 'chūzūchē', '坐车'],
                'vocabs'      => ['出租车'],
                'hsk_levels'  => [1],
            ],
            [
                'slug'        => 'transport-feiji',
                'name'        => 'Máy bay (Airplane)',
                'file_path'   => 'images/hsk/assets/transport/feiji.svg',
                'category'    => MediaAsset::CATEGORY_TRANSPORT,
                'alt_text'    => 'Máy bay hành khách bay trên trời',
                'keywords'    => ['máy bay', 'airplane', 'plane', '飞机', 'fēijī', '机场', '坐飞机'],
                'vocabs'      => ['飞机', '机场'],
                'hsk_levels'  => [1, 2],
            ],
            [
                'slug'        => 'transport-chuan',
                'name'        => 'Thuyền / Tàu thủy (Boat / Ship)',
                'file_path'   => 'images/hsk/assets/transport/chuan.svg',
                'category'    => MediaAsset::CATEGORY_TRANSPORT,
                'alt_text'    => 'Con tàu thủy lướt trên sóng nước',
                'keywords'    => ['thuyền', 'tàu thủy', 'boat', 'ship', '船', 'chuán', '坐船'],
                'vocabs'      => ['船'],
                'hsk_levels'  => [2, 3],
            ],

            // ==================== FOOD ====================
            [
                'slug'        => 'food-he-cha',
                'name'        => 'Uống trà (Drinking Tea)',
                'file_path'   => 'images/hsk/assets/food/he_cha.svg',
                'category'    => MediaAsset::CATEGORY_FOOD,
                'alt_text'    => 'Tách trà nóng bốc khói',
                'keywords'    => ['trà', 'uống trà', 'tea', '喝茶', 'hē chá', '茶', '饮料'],
                'vocabs'      => ['喝', '茶'],
                'hsk_levels'  => [1],
            ],
            [
                'slug'        => 'food-kafeiguan',
                'name'        => 'Cà phê / Quán cà phê (Coffee / Café)',
                'file_path'   => 'images/hsk/assets/food/kafeiguan.svg',
                'category'    => MediaAsset::CATEGORY_FOOD,
                'alt_text'    => 'Tách cà phê nóng',
                'keywords'    => ['cà phê', 'coffee', 'cafe', '咖啡', 'kāfēi', '咖啡馆', '喝咖啡'],
                'vocabs'      => ['咖啡'],
                'hsk_levels'  => [2, 3],
            ],
            [
                'slug'        => 'food-xi-gua',
                'name'        => 'Quả dưa hấu (Watermelon)',
                'file_path'   => 'images/hsk/assets/food/xi_gua.svg',
                'category'    => MediaAsset::CATEGORY_FOOD,
                'alt_text'    => 'Miếng dưa hấu đỏ ngọt',
                'keywords'    => ['dưa hấu', 'watermelon', '西瓜', 'xīguā', '水果', '吃西瓜'],
                'vocabs'      => ['西瓜'],
                'hsk_levels'  => [2],
            ],
            [
                'slug'        => 'food-pingguo',
                'name'        => 'Quả táo (Apple)',
                'file_path'   => 'images/hsk/assets/food/pingguo.svg',
                'category'    => MediaAsset::CATEGORY_FOOD,
                'alt_text'    => 'Quả táo đỏ',
                'keywords'    => ['quả táo', 'apple', '苹果', 'píngguǒ', '水果'],
                'vocabs'      => ['苹果'],
                'hsk_levels'  => [1],
            ],
            [
                'slug'        => 'food-shengri',
                'name'        => 'Bánh sinh nhật (Birthday Cake)',
                'file_path'   => 'images/hsk/assets/food/shengri.svg',
                'category'    => MediaAsset::CATEGORY_FOOD,
                'alt_text'    => 'Bánh kem sinh nhật cắm nến',
                'keywords'    => ['sinh nhật', 'bánh kem', 'birthday', 'cake', '生日', 'shēngrì', '蛋糕'],
                'vocabs'      => ['生日', '蛋糕'],
                'hsk_levels'  => [2, 3],
            ],

            // ==================== PEOPLE ====================
            [
                'slug'        => 'people-yisheng',
                'name'        => 'Bác sĩ (Doctor)',
                'file_path'   => 'images/hsk/assets/people/yisheng.svg',
                'category'    => MediaAsset::CATEGORY_PEOPLE,
                'alt_text'    => 'Bác sĩ đeo ống nghe',
                'keywords'    => ['bác sĩ', 'doctor', '医生', 'yīshēng', '医院', '看病'],
                'vocabs'      => ['医生', '医院'],
                'hsk_levels'  => [1, 2],
            ],
            [
                'slug'        => 'people-laoshi',
                'name'        => 'Giáo viên (Teacher)',
                'file_path'   => 'images/hsk/assets/people/laoshi.svg',
                'category'    => MediaAsset::CATEGORY_PEOPLE,
                'alt_text'    => 'Thầy giáo / Cô giáo đứng giảng bài',
                'keywords'    => ['giáo viên', 'teacher', '老师', 'lǎoshī', '学校', '教'],
                'vocabs'      => ['老师', '教'],
                'hsk_levels'  => [1, 2],
            ],
            [
                'slug'        => 'people-xuesheng',
                'name'        => 'Học sinh (Student)',
                'file_path'   => 'images/hsk/assets/people/xuesheng.svg',
                'category'    => MediaAsset::CATEGORY_PEOPLE,
                'alt_text'    => 'Học sinh đeo cặp sách',
                'keywords'    => ['học sinh', 'student', '学生', 'xuésheng', '学校', '学习'],
                'vocabs'      => ['学生', '学习'],
                'hsk_levels'  => [1, 2],
            ],
            [
                'slug'        => 'people-fuwuyuan',
                'name'        => 'Phục vụ bàn (Waiter / Server)',
                'file_path'   => 'images/hsk/assets/people/fuwuyuan.svg',
                'category'    => MediaAsset::CATEGORY_PEOPLE,
                'alt_text'    => 'Nhân viên bồi bàn cầm khay phục vụ',
                'keywords'    => ['phục vụ bàn', 'waiter', 'server', '服务员', 'fúwùyuán', '饭馆'],
                'vocabs'      => ['服务员'],
                'hsk_levels'  => [2, 3],
            ],
            [
                'slug'        => 'people-dazhen',
                'name'        => 'Khám bệnh / Tiêm thuốc (Medical / Injection)',
                'file_path'   => 'images/hsk/assets/people/dazhen.svg',
                'category'    => MediaAsset::CATEGORY_PEOPLE,
                'alt_text'    => 'Ống tiêm y tế tiêm thuốc trị bệnh',
                'keywords'    => ['tiêm thuốc', 'khám bệnh', 'injection', '打针', 'dǎzhēn', '生病', '发烧', '感冒'],
                'vocabs'      => ['生病', '发烧', '感冒'],
                'hsk_levels'  => [2, 3],
            ],

            // ==================== PLACES ====================
            [
                'slug'        => 'places-tushuguan',
                'name'        => 'Thư viện (Library)',
                'file_path'   => 'images/hsk/assets/places/tushuguan.svg',
                'category'    => MediaAsset::CATEGORY_PLACES,
                'alt_text'    => 'Kệ sách thư viện đầy sách',
                'keywords'    => ['thư viện', 'library', '图书馆', 'túshūguǎn', '借书', '看书'],
                'vocabs'      => ['图书馆', '借'],
                'hsk_levels'  => [3],
            ],
            [
                'slug'        => 'places-binguan',
                'name'        => 'Khách sạn (Hotel / Guesthouse)',
                'file_path'   => 'images/hsk/assets/places/binguan.svg',
                'category'    => MediaAsset::CATEGORY_PLACES,
                'alt_text'    => 'Tòa nhà khách sạn',
                'keywords'    => ['khách sạn', 'hotel', '宾馆', 'bīnguǎn', '饭店', '住'],
                'vocabs'      => ['宾馆', '住'],
                'hsk_levels'  => [2, 3],
            ],
            [
                'slug'        => 'places-gongsi',
                'name'        => 'Công ty / Tòa nhà văn phòng (Company)',
                'file_path'   => 'images/hsk/assets/places/gongsi.svg',
                'category'    => MediaAsset::CATEGORY_PLACES,
                'alt_text'    => 'Tòa nhà công sở công ty',
                'keywords'    => ['công ty', 'company', 'office', '公司', 'gōngsī', '上班', '工作'],
                'vocabs'      => ['公司', '上班', '工作'],
                'hsk_levels'  => [2, 3],
            ],
            [
                'slug'        => 'places-shangdian',
                'name'        => 'Cửa hàng (Store / Shop)',
                'file_path'   => 'images/hsk/assets/places/shangdian.svg',
                'category'    => MediaAsset::CATEGORY_PLACES,
                'alt_text'    => 'Mặt tiền cửa hàng mua sắm',
                'keywords'    => ['cửa hàng', 'shop', 'store', '商店', 'shāngdiàn', '买东西'],
                'vocabs'      => ['商店', '买'],
                'hsk_levels'  => [1, 2],
            ],
            [
                'slug'        => 'places-dianying',
                'name'        => 'Rạp chiếu phim (Cinema / Movie)',
                'file_path'   => 'images/hsk/assets/places/dianying.svg',
                'category'    => MediaAsset::CATEGORY_PLACES,
                'alt_text'    => 'Màn hình rạp chiếu phim và vé xem phim',
                'keywords'    => ['rạp chiếu phim', 'xem phim', 'cinema', 'movie', '电影', 'diànyǐng', '电影院'],
                'vocabs'      => ['电影', '电影院'],
                'hsk_levels'  => [1, 2],
            ],

            // ==================== OBJECTS ====================
            [
                'slug'        => 'objects-shoubiao',
                'name'        => 'Đồng hồ đeo tay (Wristwatch)',
                'file_path'   => 'images/hsk/assets/objects/shoubiao.svg',
                'category'    => MediaAsset::CATEGORY_OBJECTS,
                'alt_text'    => 'Chiếc đồng hồ đeo tay thời trang',
                'keywords'    => ['đồng hồ', 'watch', '手表', 'shǒubiǎo', '时间', '点'],
                'vocabs'      => ['手表', '时间'],
                'hsk_levels'  => [2, 3],
            ],
            [
                'slug'        => 'objects-qunzi',
                'name'        => 'Chiếc váy (Dress / Skirt)',
                'file_path'   => 'images/hsk/assets/objects/qunzi.svg',
                'category'    => MediaAsset::CATEGORY_OBJECTS,
                'alt_text'    => 'Chiếc váy áo thời trang',
                'keywords'    => ['chiếc váy', 'váy', 'dress', 'skirt', '裙子', 'qúnzi', '衣服', '穿'],
                'vocabs'      => ['裙子', '衣服', '穿'],
                'hsk_levels'  => [3],
            ],
            [
                'slug'        => 'objects-yanjing',
                'name'        => 'Kính đeo mắt (Eyeglasses)',
                'file_path'   => 'images/hsk/assets/objects/yanjing.svg',
                'category'    => MediaAsset::CATEGORY_OBJECTS,
                'alt_text'    => 'Cặp kính mắt cận thị',
                'keywords'    => ['kính mắt', 'glasses', 'eyeglasses', '眼镜', 'yǎnjìng', '看'],
                'vocabs'      => ['眼镜'],
                'hsk_levels'  => [3],
            ],
            [
                'slug'        => 'objects-shuaka',
                'name'        => 'Máy quẹt thẻ POS / Thẻ thanh toán (Card Payment)',
                'file_path'   => 'images/hsk/assets/objects/shuaka.svg',
                'category'    => MediaAsset::CATEGORY_OBJECTS,
                'alt_text'    => 'Máy quẹt thẻ thanh toán ngân hàng',
                'keywords'    => ['quẹt thẻ', 'thanh toán', 'card payment', '刷卡', 'shuākǎ', '卡', '钱'],
                'vocabs'      => ['钱'],
                'hsk_levels'  => [3],
            ],
            [
                'slug'        => 'objects-kuaidi',
                'name'        => 'Bưu kiện / Chuyển phát nhanh (Parcel / Delivery)',
                'file_path'   => 'images/hsk/assets/objects/kuaidi.svg',
                'category'    => MediaAsset::CATEGORY_OBJECTS,
                'alt_text'    => 'Hộp bưu phẩm chuyển phát nhanh dán băng keo',
                'keywords'    => ['bưu kiện', 'kiện hàng', 'parcel', 'package', '快递', 'kuàidì', '包裹'],
                'vocabs'      => ['包'],
                'hsk_levels'  => [3],
            ],
            [
                'slug'        => 'objects-chucha',
                'name'        => 'Va li hành lý / Đi công tác (Luggage Suitcase)',
                'file_path'   => 'images/hsk/assets/objects/chucha.svg',
                'category'    => MediaAsset::CATEGORY_OBJECTS,
                'alt_text'    => 'Chiếc va li du lịch có bánh xe',
                'keywords'    => ['va li', 'hành lý', 'công tác', 'suitcase', 'luggage', '行李箱', 'xínglǐxiāng', '出差'],
                'vocabs'      => ['行李箱'],
                'hsk_levels'  => [3],
            ],
            [
                'slug'        => 'objects-yizi',
                'name'        => 'Cái ghế (Chair)',
                'file_path'   => 'images/hsk/assets/objects/yizi.svg',
                'category'    => MediaAsset::CATEGORY_OBJECTS,
                'alt_text'    => 'Cái ghế dựa bằng gỗ',
                'keywords'    => ['cái ghế', 'chair', '椅子', 'yǐzi', '坐'],
                'vocabs'      => ['椅子', '坐'],
                'hsk_levels'  => [1],
            ],

            // ==================== NATURE ====================
            [
                'slug'        => 'nature-xia-yu',
                'name'        => 'Trời mưa (Raining)',
                'file_path'   => 'images/hsk/assets/nature/xia_yu.svg',
                'category'    => MediaAsset::CATEGORY_NATURE,
                'alt_text'    => 'Đám mây và hạt mưa rơi',
                'keywords'    => ['mưa', 'trời mưa', 'rain', 'raining', '下雨', 'xiàyǔ', '天气', '雨'],
                'vocabs'      => ['下雨', '雨', '天气'],
                'hsk_levels'  => [1, 2],
            ],
            [
                'slug'        => 'nature-tianqi-xue',
                'name'        => 'Tuyết rơi (Snowing)',
                'file_path'   => 'images/hsk/assets/nature/tianqi_xue.svg',
                'category'    => MediaAsset::CATEGORY_NATURE,
                'alt_text'    => 'Bông tuyết trắng mùa đông giá lạnh',
                'keywords'    => ['tuyết', 'tuyết rơi', 'snow', 'snowing', '下雪', 'xiàxuě', '雪', '冷', '天气'],
                'vocabs'      => ['雪', '冷'],
                'hsk_levels'  => [2, 3],
            ],
        ];

        foreach ($assets as $data) {
            $asset = MediaAsset::updateOrCreate(
                ['slug' => $data['slug']],
                [
                    'name'        => $data['name'],
                    'file_path'   => $data['file_path'],
                    'category'    => $data['category'],
                    'alt_text'    => $data['alt_text'],
                    'keywords'    => $data['keywords'],
                    'source'      => 'OpenMoji & Learn Chinese',
                    'license'     => 'CC BY-SA 4.0',
                    'attribution' => $defaultAttribution,
                    'metadata'    => [
                        'format'     => 'svg',
                        'style'      => 'flat_vector',
                        'hsk_levels' => $data['hsk_levels'] ?? [1, 2],
                    ],
                    'is_active'   => true,
                ]
            );

            // Connect related vocabularies if present in database
            if (!empty($data['vocabs'])) {
                foreach ($data['vocabs'] as $idx => $hanzi) {
                    $vocab = Vocabulary::where('hanzi', $hanzi)->first();
                    if ($vocab) {
                        $relationType = ($idx === 0) ? 'primary' : 'secondary';
                        $asset->vocabularies()->syncWithoutDetaching([
                            $vocab->id => ['relation_type' => $relationType],
                        ]);
                    }
                }
            }
        }
    }
}
