<?php

namespace Database\Seeders;

use App\Models\Question;
use Illuminate\Database\Seeder;

class HskMockExamQuestionSeeder extends Seeder
{
    public function run(): void
    {
        $questions = [
            // ==========================================
            // HSK 1 - PHẦN NGHE (LISTENING)
            // ==========================================
            [
                'hsk_level' => 1,
                'skill_type' => 'listening',
                'difficulty' => 'starter',
                'question' => 'Nghe đoạn âm thanh và chọn câu dịch tiếng Việt chính xác:',
                'pinyin' => 'Nǐ hǎo, wǒ shì Zhōngguórén.',
                'audio_text' => '你好，我是中国人。',
                'options' => ['Xin chào, tôi là người Trung Quốc.', 'Xin chào, tôi là người Việt Nam.', 'Tạm biệt, tôi đi Trung Quốc.', 'Chào thầy, tôi là học sinh.'],
                'correct_answer' => 'Xin chào, tôi là người Trung Quốc.',
                'explanation' => '你好 (nǐ hǎo) = Xin chào; 我是 (wǒ shì) = Tôi là; 中国人 (Zhōngguórén) = Người Trung Quốc.',
                'sort_order' => 1,
            ],
            [
                'hsk_level' => 1,
                'skill_type' => 'listening',
                'difficulty' => 'starter',
                'question' => 'Nghe và chọn số lượng được nhắc đến trong câu:',
                'pinyin' => 'Zhuōzi shàng yǒu wǔ gè píngguǒ.',
                'audio_text' => '桌子上有五个苹果。',
                'options' => ['3 quả táo', '4 quả táo', '5 quả táo', '8 quả táo'],
                'correct_answer' => '5 quả táo',
                'explanation' => '五 (wǔ) = 5; 苹果 (píngguǒ) = quả táo. Câu này có nghĩa: Trên bàn có 5 quả táo.',
                'sort_order' => 2,
            ],
            [
                'hsk_level' => 1,
                'skill_type' => 'listening',
                'difficulty' => 'starter',
                'question' => 'Nghe đoạn đối thoại ngắn và cho biết người nói muốn làm gì:',
                'pinyin' => 'Wǒ xiǎng hē chá, nǐ ne?',
                'audio_text' => '我想喝茶，你呢？',
                'options' => ['Uống nước trà', 'Uống cà phê', 'Ăn cơm', 'Đi ngủ'],
                'correct_answer' => 'Uống nước trà',
                'explanation' => '喝茶 (hē chá) = uống trà; 想 (xiǎng) = muốn.',
                'sort_order' => 3,
            ],
            [
                'hsk_level' => 1,
                'skill_type' => 'listening',
                'difficulty' => 'starter',
                'question' => 'Nghe và cho biết bây giờ là mấy giờ:',
                'pinyin' => 'Xiànzài bā diǎn bàn.',
                'audio_text' => '现在八点半。',
                'options' => ['8 giờ 30 phút', '7 giờ 30 phút', '8 giờ đúng', '9 giờ 15 phút'],
                'correct_answer' => '8 giờ 30 phút',
                'explanation' => '八点半 (bā diǎn bàn) = 8 giờ rưỡi (8:30).',
                'sort_order' => 4,
            ],
            [
                'hsk_level' => 1,
                'skill_type' => 'listening',
                'difficulty' => 'starter',
                'question' => 'Nghe và xác định thời tiết hôm nay thế nào:',
                'pinyin' => 'Jīntiān tiānqì hěn hǎo, bù lěng.',
                'audio_text' => '今天天气很好，不冷。',
                'options' => ['Thời tiết rất đẹp, không lạnh', 'Trời đang mưa to', 'Trời rất lạnh', 'Trời nhiều mây và có tuyết'],
                'correct_answer' => 'Thời tiết rất đẹp, không lạnh',
                'explanation' => '天气很好 (tiānqì hěn hǎo) = thời tiết rất đẹp; 不冷 (bù lěng) = không lạnh.',
                'sort_order' => 5,
            ],
            [
                'hsk_level' => 1,
                'skill_type' => 'listening',
                'difficulty' => 'starter',
                'question' => 'Nghe và cho biết đồ vật đang ở đâu:',
                'pinyin' => 'Shū zài yǐzi xiàmiàn.',
                'audio_text' => '书在椅子下面。',
                'options' => ['Quyển sách ở dưới cái ghế', 'Quyển sách ở trên bàn', 'Quyển sách ở trong cặp', 'Quyển sách ở trên giường'],
                'correct_answer' => 'Quyển sách ở dưới cái ghế',
                'explanation' => '书 (shū) = sách; 椅子下面 (yǐzi xiàmiàn) = dưới cái ghế.',
                'sort_order' => 6,
            ],
            [
                'hsk_level' => 1,
                'skill_type' => 'listening',
                'difficulty' => 'starter',
                'question' => 'Nghe và chọn câu đáp lại lịch sự và phù hợp nhất:',
                'pinyin' => 'Xièxie nǐ!',
                'audio_text' => '谢谢你！',
                'options' => ['不客气 (Bú kèqi)', '没关系 (Méi guānxi)', '对不起 (Duìbuqǐ)', '再见 (Zàijiàn)'],
                'correct_answer' => '不客气 (Bú kèqi)',
                'explanation' => 'Khi người khác nói 谢谢 (cảm ơn), câu đáp lại chuẩn mực là 不客气 (đừng khách sáo / không có chi).',
                'sort_order' => 7,
            ],
            [
                'hsk_level' => 1,
                'skill_type' => 'listening',
                'difficulty' => 'starter',
                'question' => 'Nghe và cho biết người nói đi đâu:',
                'pinyin' => 'Wǒ zuò chūzūchē qù yīyuàn.',
                'audio_text' => '我坐出租车去医院。',
                'options' => ['Đi bệnh viện bằng taxi', 'Đi trường học bằng xe buýt', 'Đi sân bay bằng tàu hỏa', 'Đi siêu thị mua đồ'],
                'correct_answer' => 'Đi bệnh viện bằng taxi',
                'explanation' => '坐出租车 (zuò chūzūchē) = đi taxi; 去医院 (qù yīyuàn) = đi bệnh viện.',
                'sort_order' => 8,
            ],
            [
                'hsk_level' => 1,
                'skill_type' => 'listening',
                'difficulty' => 'starter',
                'question' => 'Nghe và cho biết mối quan hệ của hai người:',
                'pinyin' => 'Tā shì wǒ de hànyǔ lǎoshī.',
                'audio_text' => '她是我的汉语老师。',
                'options' => ['Cô ấy là giáo viên tiếng Trung của tôi', 'Cô ấy là bạn học cùng lớp', 'Cô ấy là bác sĩ của tôi', 'Cô ấy là em gái tôi'],
                'correct_answer' => 'Cô ấy là giáo viên tiếng Trung của tôi',
                'explanation' => '汉语老师 (hànyǔ lǎoshī) = giáo viên tiếng Hán/Trung.',
                'sort_order' => 9,
            ],
            [
                'hsk_level' => 1,
                'skill_type' => 'listening',
                'difficulty' => 'starter',
                'question' => 'Nghe và xác nhận món đồ này giá bao nhiêu tiền:',
                'pinyin' => 'Zhè běn shū èrshí kuài qián.',
                'audio_text' => '这本书二十块钱。',
                'options' => ['20 tệ', '12 tệ', '200 tệ', '2 tệ'],
                'correct_answer' => '20 tệ',
                'explanation' => '二十块钱 (èrshí kuài qián) = 20 tệ (đồng tiền Trung Quốc).',
                'sort_order' => 10,
            ],

            // ==========================================
            // HSK 1 - PHẦN ĐỌC HIỂU (READING)
            // ==========================================
            [
                'hsk_level' => 1,
                'skill_type' => 'reading',
                'difficulty' => 'starter',
                'question' => 'Chọn từ thích hợp điền vào chỗ trống: "我 ____ 喝水。"',
                'pinyin' => 'Wǒ ____ hē shuǐ.',
                'audio_text' => null,
                'options' => ['想 (xiǎng)', '看 (kàn)', '听 (tīng)', '读 (dú)'],
                'correct_answer' => '想 (xiǎng)',
                'explanation' => '想 (xiǎng) nghĩa là "muốn", đi với động từ 喝水 (uống nước): "Tôi muốn uống nước".',
                'sort_order' => 11,
            ],
            [
                'hsk_level' => 1,
                'skill_type' => 'reading',
                'difficulty' => 'starter',
                'question' => 'Chữ Hán nào dưới đây có nghĩa là "Bác sĩ"?',
                'pinyin' => 'yī shēng',
                'audio_text' => null,
                'options' => ['医生', '老师', '学生', '朋友'],
                'correct_answer' => '医生',
                'explanation' => '医生 (yīshēng) = Bác sĩ; 老师 (lǎoshī) = Thầy/Cô giáo; 学生 (xuésheng) = Học sinh; 朋友 (péngyou) = Bạn bè.',
                'sort_order' => 12,
            ],
            [
                'hsk_level' => 1,
                'skill_type' => 'reading',
                'difficulty' => 'starter',
                'question' => 'Chọn câu có nghĩa: "Ngày mai bạn đi đâu?"',
                'pinyin' => 'Míngtiān nǐ qù nǎr?',
                'audio_text' => null,
                'options' => ['明天你去哪儿？', '昨天你去哪儿？', '今天你在哪儿？', '你什么时候去？'],
                'correct_answer' => '明天你去哪儿？',
                'explanation' => '明天 (míngtiān) = ngày mai; 你 (nǐ) = bạn; 去 (qù) = đi; 哪儿 (nǎr) = đâu.',
                'sort_order' => 13,
            ],
            [
                'hsk_level' => 1,
                'skill_type' => 'reading',
                'difficulty' => 'starter',
                'question' => 'Đọc câu sau và chọn nhận định ĐÚNG: "小明今年十八岁，他是北京大学的学生。"',
                'pinyin' => 'Xiǎomíng jīnnián shíbā suì, tā shì Běijīng Dàxué de xuésheng.',
                'audio_text' => null,
                'options' => ['Tiểu Minh 18 tuổi và là sinh viên Đại học Bắc Kinh', 'Tiểu Minh 18 tuổi và là giáo viên', 'Tiểu Minh 80 tuổi đang ở Bắc Kinh', 'Tiểu Minh là học sinh cấp 2'],
                'correct_answer' => 'Tiểu Minh 18 tuổi và là sinh viên Đại học Bắc Kinh',
                'explanation' => '十八岁 (shíbā suì) = 18 tuổi; 学生 (xuésheng) = sinh viên/học sinh.',
                'sort_order' => 14,
            ],
            [
                'hsk_level' => 1,
                'skill_type' => 'reading',
                'difficulty' => 'starter',
                'question' => 'Tìm từ trái nghĩa với từ "大" (dà - to, lớn):',
                'pinyin' => 'dà',
                'audio_text' => null,
                'options' => ['小 (xiǎo)', '多 (duō)', '少 (shǎo)', '冷 (lěng)'],
                'correct_answer' => '小 (xiǎo)',
                'explanation' => '大 (dà - lớn) trái nghĩa với 小 (xiǎo - nhỏ).',
                'sort_order' => 15,
            ],
            [
                'hsk_level' => 1,
                'skill_type' => 'reading',
                'difficulty' => 'starter',
                'question' => 'Chọn chữ Hán tương ứng với phiên âm "huí jiā" (về nhà):',
                'pinyin' => 'huí jiā',
                'audio_text' => null,
                'options' => ['回家', '看家', '在家的', '大家'],
                'correct_answer' => '回家',
                'explanation' => '回 (huí) = về; 家 (jiā) = nhà $\rightarrow$ 回家 (huí jiā) = về nhà.',
                'sort_order' => 16,
            ],
            [
                'hsk_level' => 1,
                'skill_type' => 'reading',
                'difficulty' => 'starter',
                'question' => 'Điền từ thích hợp vào câu: "爸爸在 ____ 睡觉。"',
                'pinyin' => 'Bàba zài ____ shuìjiào.',
                'audio_text' => null,
                'options' => ['房间里 (fángjiān lǐ)', '杯子里 (bēizi lǐ)', '苹果里 (píngguǒ lǐ)', '天气里 (tiānqì lǐ)'],
                'correct_answer' => '房间里 (fángjiān lǐ)',
                'explanation' => '房间里 (fángjiān lǐ) = trong phòng. Bố đang ngủ trong phòng.',
                'sort_order' => 17,
            ],
            [
                'hsk_level' => 1,
                'skill_type' => 'reading',
                'difficulty' => 'starter',
                'question' => 'Đọc đoạn thoại và chọn câu trả lời đúng:\nA: "你喜欢吃米饭吗？"\nB: "我不喜欢吃米饭，我喜欢吃面条。"\n$\rightarrow$ Người B thích ăn gì?',
                'pinyin' => 'Miàntiáo',
                'audio_text' => null,
                'options' => ['Mì sợi (面条)', 'Cơm trắng (米饭)', 'Bánh bao (包子)', 'Táo (苹果)'],
                'correct_answer' => 'Mì sợi (面条)',
                'explanation' => 'B nói: 我喜欢吃面条 (Tôi thích ăn mì sợi).',
                'sort_order' => 18,
            ],
            [
                'hsk_level' => 1,
                'skill_type' => 'reading',
                'difficulty' => 'starter',
                'question' => 'Từ nào mang nghĩa "Con mèo"?',
                'pinyin' => 'māo',
                'audio_text' => null,
                'options' => ['猫 (māo)', '狗 (gǒu)', '鸟 (niǎo)', '鱼 (yú)'],
                'correct_answer' => '猫 (māo)',
                'explanation' => '猫 (māo) = con mèo; 狗 (gǒu) = con chó; 鸟 (niǎo) = con chim; 鱼 (yú) = con cá.',
                'sort_order' => 19,
            ],
            [
                'hsk_level' => 1,
                'skill_type' => 'reading',
                'difficulty' => 'starter',
                'question' => 'Ý nghĩa của câu "没关系" (méi guānxi) là gì?',
                'pinyin' => 'méi guān xi',
                'audio_text' => null,
                'options' => ['Không sao đâu / Không có gì', 'Cảm ơn bạn', 'Tạm biệt nhé', 'Chào buổi sáng'],
                'correct_answer' => 'Không sao đâu / Không có gì',
                'explanation' => '没关系 (méi guānxi) dùng để đáp lại lời xin lỗi (对不起).',
                'sort_order' => 20,
            ],

            // ==========================================
            // HSK 1 - PHẦN NGỮ PHÁP (GRAMMAR)
            // ==========================================
            [
                'hsk_level' => 1,
                'skill_type' => 'grammar',
                'difficulty' => 'starter',
                'question' => 'Chọn lượng từ chính xác cho danh từ "书" (sách): "我买了一 ____ 书。"',
                'pinyin' => 'Wǒ mǎi le yì ____ shū.',
                'audio_text' => null,
                'options' => ['本 (běn)', '个 (gè)', '只 (zhī)', '张 (zhāng)'],
                'correct_answer' => '本 (běn)',
                'explanation' => 'Lượng từ dùng cho sách, vở, tạp chí là 本 (běn). Ví dụ: 一本书 (một quyển sách).',
                'sort_order' => 21,
            ],
            [
                'hsk_level' => 1,
                'skill_type' => 'grammar',
                'difficulty' => 'starter',
                'question' => 'Sắp xếp trật tự từ đúng trong câu tiếng Trung:',
                'pinyin' => '1. 学习 / 2. 在 / 3. 我 / 4. 学校',
                'audio_text' => null,
                'options' => ['3 - 2 - 4 - 1 (我在学校学习。)', '3 - 1 - 2 - 4 (我学习在学校。)', '2 - 4 - 1 - 3 (在学校学习我。)', '1 - 3 - 2 - 4 (学习我在学校。)'],
                'correct_answer' => '3 - 2 - 4 - 1 (我在学校学习。)',
                'explanation' => 'Cấu trúc ngữ pháp tiếng Trung: Chủ ngữ + 在 + Địa điểm + Động từ (我在学校学习 = Tôi học tập ở trường).',
                'sort_order' => 22,
            ],
            [
                'hsk_level' => 1,
                'skill_type' => 'grammar',
                'difficulty' => 'starter',
                'question' => 'Chọn vị trí đúng của phó từ phủ định "不" (bù):',
                'pinyin' => 'Wǒ (A) shì (B) yīshēng (C).',
                'audio_text' => null,
                'options' => ['Vị trí (A): 我不是医生。', 'Vị trí (B): 我是不医生。', 'Vị trí (C): 我是医生不。', 'Không thể dùng 不'],
                'correct_answer' => 'Vị trí (A): 我不是医生。',
                'explanation' => 'Phó từ phủ định 不 đứng trước động từ/tính từ: 不是 = không phải là.',
                'sort_order' => 23,
            ],
            [
                'hsk_level' => 1,
                'skill_type' => 'grammar',
                'difficulty' => 'starter',
                'question' => 'Chọn trợ từ nghi vấn tạo câu hỏi Có/Không: "你是老师 ____ ？"',
                'pinyin' => 'Nǐ shì lǎoshī ____ ?',
                'audio_text' => null,
                'options' => ['吗 (ma)', '呢 (ne)', '吧 (ba)', '的 (de)'],
                'correct_answer' => '吗 (ma)',
                'explanation' => 'Trợ từ nghi vấn 吗 đặt ở cuối câu trần thuật để biến thành câu hỏi: 你是老师吗？ (Bạn có phải giáo viên không?).',
                'sort_order' => 24,
            ],
            [
                'hsk_level' => 1,
                'skill_type' => 'grammar',
                'difficulty' => 'starter',
                'question' => 'Trợ từ kết cấu "的" (de) biểu thị quan hệ sở hữu đặt ở đâu: "Đây là sách của tôi."',
                'pinyin' => 'Zhè shì wǒ ____ shū.',
                'audio_text' => null,
                'options' => ['这是我的书。', '这是书的我。', '的这是我书。', '这是我书的。'],
                'correct_answer' => '这是我的书。',
                'explanation' => 'Cấu trúc sở hữu: Định ngữ + 的 + Trung tâm ngữ: 我的书 (sách của tôi).',
                'sort_order' => 25,
            ],
            [
                'hsk_level' => 1,
                'skill_type' => 'grammar',
                'difficulty' => 'starter',
                'question' => 'Khi muốn nói thời gian trong tiếng Trung, thứ tự sắp xếp chuẩn là gì?',
                'pinyin' => 'Năm / Tháng / Ngày',
                'audio_text' => null,
                'options' => ['Từ lớn đến nhỏ: Năm $\\rightarrow$ Tháng $\\rightarrow$ Ngày', 'Từ nhỏ đến lớn: Ngày $\\rightarrow$ Tháng $\\rightarrow$ Năm', 'Tháng $\\rightarrow$ Ngày $\\rightarrow$ Năm', 'Tuỳ ý không theo quy tắc'],
                'correct_answer' => 'Từ lớn đến nhỏ: Năm $\\rightarrow$ Tháng $\\rightarrow$ Ngày',
                'explanation' => 'Tiếng Trung luôn sắp xếp thời gian và địa điểm theo thứ tự từ lớn đến nhỏ (Năm + Tháng + Ngày + Giờ).',
                'sort_order' => 26,
            ],
            [
                'hsk_level' => 1,
                'skill_type' => 'grammar',
                'difficulty' => 'starter',
                'question' => 'Trợ từ "了" (le) trong câu "我吃苹果了。" biểu thị điều gì?',
                'pinyin' => 'Wǒ chī píngguǒ le.',
                'audio_text' => null,
                'options' => ['Hành động đã xảy ra / hoàn thành', 'Hành động đang diễn ra', 'Hành động sẽ xảy ra tương lai', 'Biểu thị sự phủ định'],
                'correct_answer' => 'Hành động đã xảy ra / hoàn thành',
                'explanation' => 'Trợ từ ngữ khí/động thái 了 biểu thị động tác đã hoàn thành hoặc có sự biến đổi trạng thái.',
                'sort_order' => 27,
            ],
            [
                'hsk_level' => 1,
                'skill_type' => 'grammar',
                'difficulty' => 'starter',
                'question' => 'Chọn lượng từ thích hợp cho "người": "三 ____ 人。"',
                'pinyin' => 'sān ____ rén.',
                'audio_text' => null,
                'options' => ['个 (gè)', '本 (běn)', '只 (zhī)', '张 (zhāng)'],
                'correct_answer' => '个 (gè)',
                'explanation' => 'Lượng từ phổ biến nhất cho người và vật thông thường là 个 (gè): 三个人 (ba người).',
                'sort_order' => 28,
            ],
            [
                'hsk_level' => 1,
                'skill_type' => 'grammar',
                'difficulty' => 'starter',
                'question' => 'Từ để hỏi giá tiền trong tiếng Trung là gì?',
                'pinyin' => 'Duōshao qián?',
                'audio_text' => null,
                'options' => ['多少钱 (duōshao qián)', '几点 (jǐ diǎn)', '谁 (shéi)', '怎么 (zěnme)'],
                'correct_answer' => '多少钱 (duōshao qián)',
                'explanation' => '多少钱 (duōshao qián) = Bao nhiêu tiền?',
                'sort_order' => 29,
            ],
            [
                'hsk_level' => 1,
                'skill_type' => 'grammar',
                'difficulty' => 'starter',
                'question' => 'Chọn câu phủ định ĐÚNG ngữ pháp cho hành động trong quá khứ: "Hôm qua tôi không đi xem phim."',
                'pinyin' => 'Zuótiān wǒ méi qù kàn diànyǐng.',
                'audio_text' => null,
                'options' => ['昨天我没去看不电影。', '昨天我没去看了电影。', '昨天我不去看了电影。', '昨天我没去电影看。'],
                'correct_answer' => '昨天我没去看了电影。',
                'explanation' => 'Phủ định của hành động đã xảy ra trong quá khứ dùng 没 / 没有 (không dùng 不).',
                'sort_order' => 30,
            ],

            // ==========================================
            // HSK 2 - NGÂN HÀNG CÂU HỎI MÔ PHỎNG
            // ==========================================
            [
                'hsk_level' => 2,
                'skill_type' => 'listening',
                'difficulty' => 'intermediate',
                'question' => 'Nghe đoạn hội thoại và cho biết hai người đang làm gì:',
                'pinyin' => 'Nǐ kàn, fúwùyuán lái le, wǒmen diǎncài ba.',
                'audio_text' => '你看，服务员来了，我们点菜吧。',
                'options' => ['Đang gọi món ở nhà hàng', 'Đang mua sắm ở siêu thị', 'Đang đợi xe buýt', 'Đang xem phim'],
                'correct_answer' => 'Đang gọi món ở nhà hàng',
                'explanation' => '服务员 (fúwùyuán) = nhân viên phục vụ; 点菜 (diǎncài) = gọi món.',
                'sort_order' => 31,
            ],
            [
                'hsk_level' => 2,
                'skill_type' => 'listening',
                'difficulty' => 'intermediate',
                'question' => 'Nghe và cho biết người nói đi làm bằng phương tiện gì:',
                'pinyin' => 'Wǒ měitiān qídānchē qù shàngbān.',
                'audio_text' => '我每天骑单车去上班。',
                'options' => ['Đi xe đạp', 'Đi tàu điện ngầm', 'Đi xe buýt', 'Đi bộ'],
                'correct_answer' => 'Đi xe đạp',
                'explanation' => '骑单车 / 骑自行车 = đi xe đạp; 去上班 = đi làm.',
                'sort_order' => 32,
            ],
            [
                'hsk_level' => 2,
                'skill_type' => 'reading',
                'difficulty' => 'intermediate',
                'question' => 'Chọn liên từ thích hợp: "虽然天气很冷，____ 他还是去跑步了。"',
                'pinyin' => 'Suīrán tiānqì hěn lěng, ____ tā háishì qù pǎobù le.',
                'audio_text' => null,
                'options' => ['但是 (dànshì)', '因为 (yīnwèi)', '所以 (suǒyǐ)', '而且 (érqiě)'],
                'correct_answer' => '但是 (dànshì)',
                'explanation' => 'Cặp liên từ nhượng bộ: 虽然...但是... (Tuy... nhưng...). "Tuy trời rất lạnh nhưng anh ấy vẫn đi chạy bộ."',
                'sort_order' => 33,
            ],
            [
                'hsk_level' => 2,
                'skill_type' => 'grammar',
                'difficulty' => 'intermediate',
                'question' => 'Cấu trúc so sánh hơn trong tiếng Trung (A 比 B + Tính từ): "Hôm nay nóng hơn hôm qua."',
                'pinyin' => 'Jīntiān bǐ zuótiān rè.',
                'audio_text' => null,
                'options' => ['今天比昨天热。', '今天比昨天很热。', '昨天比今天热。', '今天更比昨天热。'],
                'correct_answer' => '今天比昨天热。',
                'explanation' => 'Cấu trúc so sánh chữ 比: A + 比 + B + Tính từ (không dùng phó từ chỉ mức độ như 很 trước tính từ).',
                'sort_order' => 34,
            ],
            [
                'hsk_level' => 2,
                'skill_type' => 'grammar',
                'difficulty' => 'intermediate',
                'question' => 'Trợ từ "过" (guò) trong câu "我去过一次北京。" biểu thị:',
                'pinyin' => 'Wǒ qù guo yí cì Běijīng.',
                'audio_text' => null,
                'options' => ['Từng trải qua kinh nghiệm trong quá khứ', 'Đang đi ngay lúc này', 'Chuẩn bị đi trong tương lai', 'Không muốn đi'],
                'correct_answer' => 'Từng trải qua kinh nghiệm trong quá khứ',
                'explanation' => 'Động từ + 过 biểu thị đã từng làm việc gì đó: "Tôi từng đi Bắc Kinh một lần."',
                'sort_order' => 35,
            ],

            // ==========================================
            // HSK 3 - NGÂN HÀNG CÂU HỎI MÔ PHỎNG
            // ==========================================
            [
                'hsk_level' => 3,
                'skill_type' => 'listening',
                'difficulty' => 'advanced',
                'question' => 'Nghe và xác định lý do nhân vật không thể tham gia buổi họp:',
                'pinyin' => 'Duìbuqǐ, wǒ jīntiān gǎnmào fāshāo le, yàoxiàng lǎobǎn qǐngjià.',
                'audio_text' => '对不起，我今天感冒发烧了，要向老板请假。',
                'options' => ['Bị cảm sốt phải xin nghỉ phép', 'Bị trễ chuyến bay', 'Đi công tác xa', 'Xe bị hỏng giữa đường'],
                'correct_answer' => 'Bị cảm sốt phải xin nghỉ phép',
                'explanation' => '感冒 (gǎnmào) = bị cảm; 发烧 (fāshāo) = sốt; 请假 (qǐngjià) = xin nghỉ phép.',
                'sort_order' => 36,
            ],
            [
                'hsk_level' => 3,
                'skill_type' => 'reading',
                'difficulty' => 'advanced',
                'question' => 'Chọn cặp từ biểu thị nguyên nhân - kết quả: "____ 昨天睡得太晚，____ 今天早上起不来。"',
                'pinyin' => '____ zuótiān shuì de tài wǎn, ____ jīntiān zǎoshang qǐ bu lái.',
                'audio_text' => null,
                'options' => ['因为...所以... (yīnwèi... suǒyǐ...)', '不但...而且... (búdàn... érqiě...)', '如果...就... (rúguǒ... jiù...)', '只要...就... (zhǐyào... jiù...)'],
                'correct_answer' => '因为...所以... (yīnwèi... suǒyǐ...)',
                'explanation' => '因为...所以... biểu thị "Bởi vì... cho nên...": Bởi vì hôm qua ngủ quá muộn nên sáng nay dậy không nổi.',
                'sort_order' => 37,
            ],
            [
                'hsk_level' => 3,
                'skill_type' => 'grammar',
                'difficulty' => 'advanced',
                'question' => 'Cấu trúc câu chữ 把 (câu xử lý): "Hãy mang quyển sách đưa cho thầy giáo."',
                'pinyin' => 'Bǎ shū gěi lǎoshī.',
                'audio_text' => null,
                'options' => ['请把这本书交给老师。', '请给老师把这本书交。', '把请这本书交给老师。', '这本书请交给把老师。'],
                'correct_answer' => '请把这本书交给老师。',
                'explanation' => 'Cấu trúc câu chữ 把: Chủ ngữ + 把 + Tân ngữ + Động từ + Thành phần khác.',
                'sort_order' => 38,
            ],
        ];

        foreach ($questions as $q) {
            Question::updateOrCreate(
                [
                    'question' => $q['question'],
                    'pinyin'   => $q['pinyin'],
                ],
                [
                    'hsk_level'      => $q['hsk_level'],
                    'skill_type'     => $q['skill_type'],
                    'difficulty'     => $q['difficulty'],
                    'audio_text'     => $q['audio_text'],
                    'options'        => $q['options'],
                    'correct_answer' => $q['correct_answer'],
                    'explanation'    => $q['explanation'],
                    'sort_order'     => $q['sort_order'],
                    'is_active'      => true,
                ]
            );
        }
    }
}
