<?php

namespace Database\Seeders;

use App\Models\Setting;
use Illuminate\Database\Seeder;

class SettingSeeder extends Seeder
{
    public function run(): void
    {
        $settings = [
            // ─── 🌐 Website ────────────────────────────────────────────────
            [
                'key'         => 'site_name',
                'value'       => 'Learn Chinese',
                'group'       => 'website',
                'type'        => 'text',
                'label'       => 'Tên website',
                'description' => 'Tên hiển thị của website trên toàn bộ giao diện.',
                'is_public'   => true,
                'is_editable' => true,
                'sort_order'  => 1,
            ],
            [
                'key'         => 'site_slogan',
                'value'       => 'Học tiếng Trung thông minh mỗi ngày',
                'group'       => 'website',
                'type'        => 'text',
                'label'       => 'Slogan',
                'description' => 'Câu slogan ngắn gọn mô tả website.',
                'is_public'   => true,
                'is_editable' => true,
                'sort_order'  => 2,
            ],
            [
                'key'         => 'contact_email',
                'value'       => '',
                'group'       => 'website',
                'type'        => 'text',
                'label'       => 'Email liên hệ',
                'description' => 'Email hiển thị để học viên liên hệ hỗ trợ.',
                'is_public'   => true,
                'is_editable' => true,
                'sort_order'  => 3,
            ],
            [
                'key'         => 'allow_registration',
                'value'       => '1',
                'group'       => 'website',
                'type'        => 'boolean',
                'label'       => 'Cho phép đăng ký mới',
                'description' => 'Nếu tắt, trang /register sẽ hiển thị thông báo đóng đăng ký.',
                'is_public'   => false,
                'is_editable' => true,
                'sort_order'  => 4,
            ],
            [
                'key'         => 'maintenance_mode',
                'value'       => '0',
                'group'       => 'website',
                'type'        => 'boolean',
                'label'       => 'Chế độ bảo trì',
                'description' => 'Bật để hiển thị trang bảo trì cho học viên. Admin vẫn truy cập được.',
                'is_public'   => false,
                'is_editable' => true,
                'sort_order'  => 5,
            ],
            [
                'key'         => 'maintenance_message',
                'value'       => 'Website đang được nâng cấp. Vui lòng quay lại sau ít phút!',
                'group'       => 'website',
                'type'        => 'text',
                'label'       => 'Thông báo bảo trì',
                'description' => 'Nội dung hiển thị trên trang bảo trì.',
                'is_public'   => false,
                'is_editable' => true,
                'sort_order'  => 6,
            ],

            // ─── 📢 Announcement ───────────────────────────────────────────
            [
                'key'         => 'announcement_enabled',
                'value'       => '0',
                'group'       => 'announcement',
                'type'        => 'boolean',
                'label'       => 'Bật thông báo',
                'description' => 'Hiển thị banner thông báo ở đầu trang học viên.',
                'is_public'   => false,
                'is_editable' => true,
                'sort_order'  => 1,
            ],
            [
                'key'         => 'announcement_type',
                'value'       => 'info',
                'group'       => 'announcement',
                'type'        => 'select',
                'label'       => 'Loại thông báo',
                'description' => 'Màu sắc của banner: info (xanh), success (xanh lá), warning (vàng), error (đỏ).',
                'is_public'   => false,
                'is_editable' => true,
                'sort_order'  => 2,
            ],
            [
                'key'         => 'announcement_title',
                'value'       => '',
                'group'       => 'announcement',
                'type'        => 'text',
                'label'       => 'Tiêu đề thông báo',
                'description' => 'Tiêu đề ngắn gọn của banner (tuỳ chọn).',
                'is_public'   => false,
                'is_editable' => true,
                'sort_order'  => 3,
            ],
            [
                'key'         => 'announcement_content',
                'value'       => '',
                'group'       => 'announcement',
                'type'        => 'text',
                'label'       => 'Nội dung thông báo',
                'description' => 'Nội dung đầy đủ của banner thông báo.',
                'is_public'   => false,
                'is_editable' => true,
                'sort_order'  => 4,
            ],
            [
                'key'         => 'announcement_audience',
                'value'       => 'all',
                'group'       => 'announcement',
                'type'        => 'select',
                'label'       => 'Đối tượng hiển thị',
                'description' => 'all = tất cả, guests = chưa đăng nhập, authenticated = đã đăng nhập.',
                'is_public'   => false,
                'is_editable' => true,
                'sort_order'  => 5,
            ],
            [
                'key'         => 'announcement_start',
                'value'       => null,
                'group'       => 'announcement',
                'type'        => 'datetime',
                'label'       => 'Thời gian bắt đầu',
                'description' => 'Để trống nếu hiện ngay. Định dạng: YYYY-MM-DD HH:MM',
                'is_public'   => false,
                'is_editable' => true,
                'sort_order'  => 6,
            ],
            [
                'key'         => 'announcement_end',
                'value'       => null,
                'group'       => 'announcement',
                'type'        => 'datetime',
                'label'       => 'Thời gian kết thúc',
                'description' => 'Để trống nếu hiển thị vô thời hạn.',
                'is_public'   => false,
                'is_editable' => true,
                'sort_order'  => 7,
            ],
            [
                'key'         => 'announcement_dismissible',
                'value'       => '1',
                'group'       => 'announcement',
                'type'        => 'boolean',
                'label'       => 'Cho phép đóng banner',
                'description' => 'Học viên có thể đóng banner. Trạng thái lưu trong localStorage.',
                'is_public'   => false,
                'is_editable' => true,
                'sort_order'  => 8,
            ],

            // ─── 🎓 Learning ───────────────────────────────────────────────
            [
                'key'         => 'flashcard_daily_limit',
                'value'       => '50',
                'group'       => 'learning',
                'type'        => 'integer',
                'label'       => 'Giới hạn flashcard mỗi ngày',
                'description' => 'Số flashcard tối đa học viên có thể ôn tập mỗi ngày. 0 = không giới hạn.',
                'is_public'   => false,
                'is_editable' => true,
                'sort_order'  => 1,
            ],
            [
                'key'         => 'streak_reset_hour',
                'value'       => '0',
                'group'       => 'learning',
                'type'        => 'integer',
                'label'       => 'Giờ reset streak (0–23)',
                'description' => 'Giờ trong ngày để kiểm tra và reset streak học tập (theo múi giờ hệ thống).',
                'is_public'   => false,
                'is_editable' => true,
                'sort_order'  => 2,
            ],
            [
                'key'         => 'default_daily_goal',
                'value'       => '20',
                'group'       => 'learning',
                'type'        => 'integer',
                'label'       => 'Mục tiêu học mặc định mỗi ngày',
                'description' => 'Số từ/bài học viên nên học mỗi ngày (hiển thị trong dashboard).',
                'is_public'   => false,
                'is_editable' => true,
                'sort_order'  => 3,
            ],

            // ─── 🚀 Features (Feature Flags) ──────────────────────────────
            [
                'key'         => 'feature_flashcards',
                'value'       => '1',
                'group'       => 'features',
                'type'        => 'boolean',
                'label'       => 'Thẻ ghi nhớ (Flashcards)',
                'description' => 'Bật/tắt toàn bộ tính năng ôn tập thẻ nhớ.',
                'is_public'   => false,
                'is_editable' => true,
                'sort_order'  => 1,
            ],
            [
                'key'         => 'feature_quiz',
                'value'       => '1',
                'group'       => 'features',
                'type'        => 'boolean',
                'label'       => 'Luyện tập nhanh (Quiz)',
                'description' => 'Bật/tắt tính năng quiz trắc nghiệm.',
                'is_public'   => false,
                'is_editable' => true,
                'sort_order'  => 2,
            ],
            [
                'key'         => 'feature_dictionary',
                'value'       => '1',
                'group'       => 'features',
                'type'        => 'boolean',
                'label'       => 'Từ điển & Video (YouGlish)',
                'description' => 'Bật/tắt tính năng tra từ điển và video YouGlish.',
                'is_public'   => false,
                'is_editable' => true,
                'sort_order'  => 3,
            ],
            [
                'key'         => 'feature_stories',
                'value'       => '1',
                'group'       => 'features',
                'type'        => 'boolean',
                'label'       => 'Luyện đọc hiểu (Stories)',
                'description' => 'Bật/tắt tính năng đọc truyện Graded Reader.',
                'is_public'   => false,
                'is_editable' => true,
                'sort_order'  => 4,
            ],
            [
                'key'         => 'feature_hsk_mock',
                'value'       => '1',
                'group'       => 'features',
                'type'        => 'boolean',
                'label'       => 'Thi thử HSK',
                'description' => 'Bật/tắt tính năng thi thử mô phỏng HSK.',
                'is_public'   => false,
                'is_editable' => true,
                'sort_order'  => 5,
            ],
        ];

        foreach ($settings as $data) {
            Setting::updateOrCreate(['key' => $data['key']], $data);
        }
    }
}
